version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mhtorneria
      POSTGRES_PASSWORD: Silmampabas6245.
      POSTGRES_DB: mapadventure
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mh.torneria@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Silmampabas6245.
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
